// لیست کشورها — فارسی برای شرکت‌های داخلی/منطقه، انگلیسی برای شرکت‌های خارجی
// (چک‌باکس داخلی/خارجی در فرم شرکت تعیین می‌کنه کدوم ستون نمایش داده بشه)

export interface Country {
  fa: string;
  en: string;
}

export const COUNTRIES: Country[] = [
  { fa: "ایران", en: "Iran" },
  { fa: "آلمان", en: "Germany" },
  { fa: "ایتالیا", en: "Italy" },
  { fa: "ترکیه", en: "Turkey" },
  { fa: "چین", en: "China" },
  { fa: "امارات متحده عربی", en: "United Arab Emirates" },
  { fa: "هلند", en: "Netherlands" },
  { fa: "فرانسه", en: "France" },
  { fa: "انگلستان", en: "United Kingdom" },
  { fa: "اسپانیا", en: "Spain" },
  { fa: "سوئد", en: "Sweden" },
  { fa: "سوئیس", en: "Switzerland" },
  { fa: "اتریش", en: "Austria" },
  { fa: "بلژیک", en: "Belgium" },
  { fa: "لهستان", en: "Poland" },
  { fa: "چک", en: "Czech Republic" },
  { fa: "روسیه", en: "Russia" },
  { fa: "هند", en: "India" },
  { fa: "ژاپن", en: "Japan" },
  { fa: "کره جنوبی", en: "South Korea" },
  { fa: "تایوان", en: "Taiwan" },
  { fa: "آمریکا", en: "United States" },
  { fa: "کانادا", en: "Canada" },
  { fa: "برزیل", en: "Brazil" },
  { fa: "استرالیا", en: "Australia" },
  { fa: "عراق", en: "Iraq" },
  { fa: "افغانستان", en: "Afghanistan" },
  { fa: "پاکستان", en: "Pakistan" },
  { fa: "ترکمنستان", en: "Turkmenistan" },
  { fa: "آذربایجان", en: "Azerbaijan" },
  { fa: "ارمنستان", en: "Armenia" },
  { fa: "گرجستان", en: "Georgia" },
  { fa: "قزاقستان", en: "Kazakhstan" },
  { fa: "ازبکستان", en: "Uzbekistan" },
  { fa: "عمان", en: "Oman" },
  { fa: "قطر", en: "Qatar" },
  { fa: "کویت", en: "Kuwait" },
  { fa: "عربستان سعودی", en: "Saudi Arabia" },
  { fa: "بحرین", en: "Bahrain" },
  { fa: "مالزی", en: "Malaysia" },
  { fa: "سنگاپور", en: "Singapore" },
  { fa: "اندونزی", en: "Indonesia" },
  { fa: "تایلند", en: "Thailand" },
  { fa: "ویتنام", en: "Vietnam" },
  { fa: "مصر", en: "Egypt" },
  { fa: "آفریقای جنوبی", en: "South Africa" },
  { fa: "یونان", en: "Greece" },
  { fa: "پرتغال", en: "Portugal" },
  { fa: "دانمارک", en: "Denmark" },
  { fa: "نروژ", en: "Norway" },
  { fa: "فنلاند", en: "Finland" },
  { fa: "مجارستان", en: "Hungary" },
  { fa: "رومانی", en: "Romania" },
  { fa: "بلغارستان", en: "Bulgaria" },
  { fa: "صربستان", en: "Serbia" },
  { fa: "اوکراین", en: "Ukraine" },
  { fa: "بلاروس", en: "Belarus" },
  { fa: "اسلواکی", en: "Slovakia" },
  { fa: "اسلوونی", en: "Slovenia" },
  { fa: "کرواسی", en: "Croatia" },
  { fa: "ایرلند", en: "Ireland" },
  { fa: "لوکزامبورگ", en: "Luxembourg" },
  { fa: "مکزیک", en: "Mexico" },
  { fa: "آرژانتین", en: "Argentina" },
  { fa: "شیلی", en: "Chile" },
];
